#pragma once

#include <reflection/reflection.h>



REFLECTABLE_OPERATOR(operator[]);
REFLECTABLE_OPERATOR_ASSIGNMENT(=);
REFLECTABLE_OPERATOR_INFIX(+);
REFLECTABLE_OPERATOR_INFIX(<<);
REFLECTABLE_OPERATOR_INFIX(==);
